
esphome:
  name: can-node-1

external_components:
  - source: ../components
  #- source: github://mrk-its/esphome-canopen

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s

ota:
  password: ""

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  <<: !include {file: wifi.yaml}

canbus:
  - platform: esp32_can
    id: can_bus
    rx_pin: GPIO22
    tx_pin: GPIO23
    can_id: 0
    bit_rate: 125kbps

canopen:
  id: can_gate
  canbus_id: can_bus
  node_id: 1
  entities:
    - id: boot
      index: 1
      tpdo: 0
    - id: uptime_sensor
      index: 3
      tpdo: 0
    - id: cover1
      index: 4
      tpdo: 1
    - id: blue_light
      index: 5
      tpdo: 1
      rpdo:
        - node_id: 2
          tpdo: 1
          offset: 2

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime 1"
    update_interval: 5sec
    internal: true

binary_sensor:
  - platform: gpio
    name: "Boot 1"
    id: boot
    internal: true
    pin:
      number: GPIO0
      inverted: true

switch:
  - platform: gpio
    name: "GPIO Switch"
    id: gpio_switch
    internal: true
    pin: GPIO16

cover:
  - platform: time_based
    name: "Cover 1"
    id: cover1
    internal: true
    device_class: shutter
    has_built_in_endstop: true
    open_action:
      - logger.log: open_action
    open_duration: 10s
    close_action:
      - logger.log: close_action
    close_duration: 10s
    stop_action:
      - logger.log: stop_action

output:
  - platform: ledc
    pin: GPIO2
    id: blue_led

light:
  - platform: monochromatic
    name: "PWM Blue Led"
    output: blue_led
    id: blue_light
    default_transition_length: 500ms
    internal: true